name: Deploy

on:
  push:
    branches: [ main ]

env:
  repositoryDir: D:\Clones\EarthApi
  projectDir: D:\Clones\EarthApi\EarthApi\EarthApi
  destinationDir: D:\Websites\EarthApi
  publishDir: D:\Clones\EarthApi\EarthApi\EarthApi\bin\Release\net9.0\publish

jobs:
  test-runner:
    runs-on: self-hosted  # This will use your self-hosted runner
    
    steps:
    - name: Pull Repository
      shell: powershell
      run: |
        Write-Host "Going to repository directory..."
        cd "${{ env.repositoryDir }}"
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Pulling latest code..."
        git pull origin main

    - name: Build
      shell: powershell
      run: |
        Write-Host "Going to project directory..."
        cd "${{ env.projectDir }}"
        Write-Host "Building"
        dotnet build
      

    - name: Deploy Application
      shell: powershell
      run: |
        Write-Host "Going to project directory..."
        cd "${{ env.projectDir }}"
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Publish application..."
        dotnet publish
        Write-Host "Publish completed successfully!"
        Write-Host "Ready to copy build to deployment directory..."
        Copy-Item -Path "${{ env.publishDir }}/*" -Destination "${{ env.destinationDir }}" -Recurse -Force
